// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCQ6EWAkMZjVM5xAbZdsRh20i4WVj5uUk',
    appId: '1:358765796312:web:f5b17fb79aefce93d6b0ad',
    messagingSenderId: '358765796312',
    projectId: 'app-vendas-1d9cc',
    authDomain: 'app-vendas-1d9cc.firebaseapp.com',
    storageBucket: 'app-vendas-1d9cc.firebasestorage.app',
    measurementId: 'G-R5PL0MC9YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgTiG62_8BHNKPiwDeWx8VdqU1yy7oP34',
    appId: '1:358765796312:android:d37860a998b25a10d6b0ad',
    messagingSenderId: '358765796312',
    projectId: 'app-vendas-1d9cc',
    storageBucket: 'app-vendas-1d9cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBga1Zf1Y0BOAjGZGRKytPtcvc2ZCBtpoY',
    appId: '1:358765796312:ios:db857b21227cf60dd6b0ad',
    messagingSenderId: '358765796312',
    projectId: 'app-vendas-1d9cc',
    storageBucket: 'app-vendas-1d9cc.firebasestorage.app',
    iosBundleId: 'com.example.appVendas',
  );
}
